# Main info
app_name: "WebsiteName"
town_name: "YourTown"
contant_email: "website_owner@email.com" # This will apear in tha Contact information
defaut_locale: "en" # Language support


google_analytics: "<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-45655854-1', 'lamiatodo.gr');ga('send', 'pageview');</script>"
# Put here the script Google Analytics has provided you with. With <tags> and such.
# Spaces dont matter but keep things tidy. And you can leave this empty if you dont want Analytics

# Deploy info
server_ip: "11.111.11.110"
server_user: "my_user"

# Mailer config
# You need this for mailing functions to work
action_mailer_address: "smtp.gmail.com" # For Gmail
action_mailer_port: 587
action_mailer_domain: "websitedomain.com" 
action_mailer_username: "gmail_user"        # If you use gmail you can put your username
action_mailer_password: "secure_password!"  # and password here for mailer to work

developement:
  action_mailer_host: "localhost:3000"
test:
  action_mailer_host: "localhost:3000"
production:
  action_mailer_host: "Your_Server_IP"

# Notification Mailer 
default_from: "no_reply@website.com"
default_to: "your_email@example.com" # Feedback by users will be send here


# SEO Tags seperate by ","  (Not yet implemented)
seo_tags:


# Authentication Config
device_secret_key:
device_mailer:

# Oauth Authentication (Defaults to LocalGrowth apps, they are for testing you should make your own apps with the name of your website)
facebook_app_id: "448298675275606"
facebook_app_secret: "b94f40817884784d23d1fce3e873814d"
google_maps_id:
google_maps_secret:
